name: First

on: ["push"]

jobs:
    job1:
      name: "My first job "
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: python eati.py EATI 2023    
            

    job2:
      name: "My second job"
      runs-on: windows-latest
      steps:
        - run: |
            echo "mi nombre es Manuel"
            echo "Estoy haciendo un curso de Github Actions"
